# 2.1 A first look at a neural network

## Listing 2.1 Loading the MNIST dataset in Keras

In [19]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [4]:
train_images.shape

(60000, 28, 28)

In [6]:
len(train_labels)

60000

In [7]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
test_images.shape

(10000, 28, 28)

In [9]:
len(test_labels)

10000

In [10]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

## 2.2 The network architecture

In [20]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

## Listing 2.3 The compilation step

In [21]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

## Listing 2.4 Preparing the image data

In [22]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

## 2.5 "Fitting" the model

In [23]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 1s 3ms/step - loss: 0.2564 - accuracy: 0.9256
Epoch 2/5
469/469 [==============================] - 1s 3ms/step - loss: 0.1032 - accuracy: 0.9689
Epoch 3/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0676 - accuracy: 0.9797
Epoch 4/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0493 - accuracy: 0.9851
Epoch 5/5
469/469 [==============================] - 1s 3ms/step - loss: 0.0372 - accuracy: 0.9890


## 2.6 Using the model to make predictions

In [24]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 40ms/step


array([1.4960789e-09, 2.2377208e-10, 5.9952839e-07, 5.8490441e-06,
       8.8263050e-13, 2.9617533e-09, 2.8872934e-14, 9.9999344e-01,
       9.0959116e-09, 1.6139059e-07], dtype=float32)

## Listing 2.7 Evaluating the model on new data

In [25]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc:{test_acc}")


313/313 [==============================] - 0s 610us/step - loss: 0.0659 - accuracy: 0.9812
test_acc:0.9811999797821045


# 2.2 Data representations for neural networks

## 2.2.1 Scalars (rank-0 tensors)